require:
  - rubocop-performance

AllCops:
  Exclude:
    - "test/**/*"
    - "tests/**/*"
    - "spec/**/*"
    - "vendor/**/*"
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.5

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - lib/smart_proxy_reports/puppet_processor.rb
